/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * Run `pnpm generate:types` to regenerate.
 */

export interface Config {
  auth: { users: UserAuthOperations };
  blocks: Record<string, never>;
  collections: {
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: Record<string, never>;
  collectionsSelect: Record<string, unknown>;
  db: { defaultIDType: string };
  fallbackLocale: null;
  globals: Record<string, never>;
  globalsSelect: Record<string, never>;
  locale: null;
  user: User;
  jobs: { tasks: unknown; workflows: unknown };
}

export interface UserAuthOperations {
  forgotPassword: { email: string; password: string };
  login: { email: string; password: string };
  registerFirstUser: { email: string; password: string };
  unlock: { email: string; password: string };
}

export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?: { id: string; createdAt?: string | null; expiresAt: string }[] | null;
  password?: string | null;
  collection: 'users';
}

export interface PayloadKv {
  id: string;
  key: string;
  data: Record<string, unknown> | unknown[] | string | number | boolean | null;
}

export interface PayloadLockedDocument {
  id: string;
  document?: unknown;
  globalSlug?: string | null;
  user: { relationTo: 'users'; value: string | User };
  updatedAt: string;
  createdAt: string;
}

export interface PayloadPreference {
  id: string;
  user: { relationTo: 'users'; value: string | User };
  key?: string | null;
  value?: Record<string, unknown> | unknown[] | string | number | boolean | null;
  updatedAt: string;
  createdAt: string;
}

export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
